scalar Time
scalar ObjectID

schema {
  query: Query
  subscription: Subscription
  mutation: Mutation
}

directive @goField(
  forceResolver: Boolean
  name: String
) on INPUT_FIELD_DEFINITION | FIELD_DEFINITION
